version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    command: "yarn dev"
    ports: 
      - "4001:3000"
      